export const SESSION_SENTINEL_WORKER_ARG = "__omp_worker_session_sentinel";
export const SESSION_SENTINEL_PARENT_PID_ENV = "OMP_SESSION_SENTINEL_PARENT_PID";
export const SESSION_SENTINEL_SESSION_FILE_ENV = "OMP_SESSION_SENTINEL_SESSION_FILE";
